import type { SegmentContract, SegmentThresholds, Signals } from "./types.js";

export const SEGMENT_NAME = "Stalled Shortlister";
export const PREVIOUS_SEGMENT_NAME = "P1 Wishlist Staller";

/**
 * Phase 4 owns the contract; Phase 5a owns the implementation. This source is
 * emitted as an artefact so `apps/mvp/lib/segment.ts` has one place to copy
 * from and cannot drift from the thresholds the evidence supports.
 */
function renderSource(thresholds: SegmentThresholds): string {
  return `// Generated by phase-4. Contract only — Phase 5a implements this against real user data.
export function matchesStalledShortlister(user: User): boolean {
  if (user.optedOut) return false;

  const recent = user.wishlistItems.filter((i) => i.addedWithinDays(${thresholds.windowDays}));
  if (recent.length < ${thresholds.minRecentSaves}) return false;

  const purchased = recent.filter((i) => i.purchasedWithinDays(${thresholds.windowDays}));
  if (purchased.length > ${thresholds.maxPurchasedInWindow}) return false;

  const byCategory = groupByCategory(recent);
  return Object.values(byCategory).some((count) => count >= ${thresholds.minSameCategory});
}
`;
}

/**
 * Thresholds come from the save-volume distribution rather than from taste. A
 * three-item floor was the Phase 2 draft; it excludes most of the sample, so it
 * drops to two whenever the modal bucket tops out at five saves or fewer.
 */
export function deriveThresholds(signals: Signals): {
  thresholds: SegmentThresholds;
  derivation: string[];
} {
  const small = signals.saveVolume.majorityAtOrBelowFive;
  const floor = small ? 2 : 3;
  const modal = signals.saveVolume.modalBucket ?? "unknown";
  const modalCount =
    signals.saveVolume.buckets.find((bucket) => bucket.answer === modal)?.count ?? 0;

  const derivation = [
    `Window stays 30 days: W2P 30d is the north-star metric, so eligibility is measured on the same clock.`,
    small
      ? `Save floor lowered from 3 to ${floor}: the modal bucket is "${modal}" (${modalCount}/${signals.respondents}), and a three-item floor would exclude most of the population.`
      : `Save floor stays 3: the modal bucket is "${modal}" (${modalCount}/${signals.respondents}), which supports it.`,
    `Comparison signal set to ${floor} items in one category: two comparable options are enough to be stuck between them, and ${signals.statedVsRevealed.comparesInApp.count}/${signals.respondents} compare inside the app.`,
    `At most one purchase in the window: the segment is defined by the stall, and ${signals.segment.stalls.count}/${signals.respondents} convert sometimes or less.`,
    `Opt-out is checked first, before any wishlist data is read.`
  ];

  return {
    thresholds: {
      windowDays: 30,
      minRecentSaves: floor,
      maxPurchasedInWindow: 1,
      minSameCategory: floor
    },
    derivation
  };
}

export function segmentContract(signals: Signals): SegmentContract {
  const { thresholds, derivation } = deriveThresholds(signals);

  return {
    name: SEGMENT_NAME,
    previousName: PREVIOUS_SEGMENT_NAME,
    thresholds,
    derivation,
    controlPersona:
      "S3 sale-watchers — held as a control, never the coach audience. " +
      `${signals.statedVsRevealed.saleWaitOnly.count}/${signals.respondents} wait for a sale and do nothing else.`,
    implementedIn: "apps/mvp/lib/segment.ts (Phase 5a)",
    interfaceOnly: true,
    source: renderSource(thresholds)
  };
}

/**
 * Reference implementation of the contract above. It exists so the tests can
 * execute the thresholds instead of eyeballing them; the shipped predicate is
 * Phase 5a's job.
 */
export interface CandidateItem {
  addedDaysAgo: number;
  purchasedDaysAgo?: number;
  category: string;
}

export interface Candidate {
  optedOut?: boolean;
  wishlistItems: CandidateItem[];
}

export function referenceMatches(
  candidate: Candidate,
  thresholds: SegmentThresholds
): boolean {
  if (candidate.optedOut) return false;

  const recent = candidate.wishlistItems.filter(
    (item) => item.addedDaysAgo <= thresholds.windowDays
  );
  if (recent.length < thresholds.minRecentSaves) return false;

  const purchased = recent.filter(
    (item) =>
      item.purchasedDaysAgo !== undefined && item.purchasedDaysAgo <= thresholds.windowDays
  );
  if (purchased.length > thresholds.maxPurchasedInWindow) return false;

  const byCategory = new Map<string, number>();
  for (const item of recent) {
    byCategory.set(item.category, (byCategory.get(item.category) ?? 0) + 1);
  }
  return [...byCategory.values()].some((count) => count >= thresholds.minSameCategory);
}
