import { bad, fromZod, guardWebhook, ok } from "@/lib/http";
import { sanitizeReviewText } from "@/lib/guardrails";
import { getProductRecord, upsertProduct } from "@/lib/repo";
import { ReviewRecordSchema } from "@/lib/schemas";
import { z } from "zod";

export const dynamic = "force-dynamic";

const BodySchema = z.object({
  productId: z.string().min(1),
  reviews: z.array(ReviewRecordSchema).min(1).max(200)
});

/**
 * Tier 3 of the ingest ladder, driven by n8n or the collect UI.
 *
 * Note the boundary: this enriches the *product* review corpus that the coach
 * reads. The discovery corpus in `Phase-1/data/discovery` is regenerated by the
 * Phase 1 pipeline, which is a local or Actions job — a serverless function
 * cannot write back into the repo.
 */
export async function POST(request: Request) {
  const denied = guardWebhook(request);
  if (denied) return denied;

  let payload: unknown;
  try {
    payload = await request.json();
  } catch {
    return bad("Body must be JSON.");
  }

  const parsed = BodySchema.safeParse(payload);
  if (!parsed.success) return fromZod(parsed.error);

  const product = await getProductRecord(parsed.data.productId);
  if (!product) return bad(`Unknown product: ${parsed.data.productId}`, 404);

  const existing = new Set(product.reviews.map((review) => review.id));
  const incoming = parsed.data.reviews
    .filter((review) => !existing.has(review.id))
    .map((review) => ({ ...review, text: sanitizeReviewText(review.text) }));

  const updated = { ...product, reviews: [...product.reviews, ...incoming] };
  await upsertProduct(updated);

  return ok({
    productId: product.id,
    added: incoming.length,
    skippedAsDuplicate: parsed.data.reviews.length - incoming.length,
    totalReviews: updated.reviews.length
  });
}
