import { readFile } from "node:fs/promises";
import path from "node:path";

/**
 * Phase 5 does not restate earlier phases, it reads them. Everything here comes
 * from artefacts generated by Phases 1–4, so the MVP and the write-up cannot
 * disagree.
 */

export function repoRoot(): string {
  return path.resolve(process.cwd(), "..");
}

export function discoveryDir(): string {
  return path.join(repoRoot(), "Phase-1", "data", "discovery");
}

export function surveyDir(): string {
  return path.join(repoRoot(), "Phase-1", "data", "survey");
}

export function phase4Dir(): string {
  return path.join(repoRoot(), "phase-4", "data");
}

export function phase2Dir(): string {
  return path.join(repoRoot(), "phase-2", "data");
}

async function readJson<T>(file: string): Promise<T | null> {
  try {
    return JSON.parse(await readFile(file, "utf8")) as T;
  } catch {
    return null;
  }
}

export interface DiscoveryTheme {
  id: string;
  label: string;
  summary: string;
  barrierType: string;
  metricNode: string;
  segmentHints?: string[];
  actionableInsight?: string;
  quotes?: Array<{ text: string; reviewId: string; source: string; url?: string }>;
  researchQuestionIds?: number[];
  estimatedFrequency?: number;
}

export interface RankedTheme {
  themeId: string;
  label: string;
  barrierType: string;
  metricNode: string;
  score: number;
  rank: number;
  priceFlag: boolean;
  estimatedFrequency: number;
}

export interface DiscoveryStats {
  readyForPhase2: boolean;
  validatedThemeCount: number;
  rawCount: number;
  normalizedCount: number;
  extractionMethod: string;
  generatedAt?: string;
}

export const loadThemes = () => readJson<DiscoveryTheme[]>(path.join(discoveryDir(), "themes.json"));
export const loadRanking = () =>
  readJson<RankedTheme[]>(path.join(discoveryDir(), "opportunity-ranking.json"));
export const loadDiscoveryStats = () =>
  readJson<DiscoveryStats>(path.join(discoveryDir(), "pipeline-stats.json"));
export const loadProblemDefinition = () =>
  readJson<Record<string, unknown>>(path.join(phase4Dir(), "problem-definition.json"));
export const loadDecisionTree = () =>
  readJson<Record<string, unknown>>(path.join(phase4Dir(), "decision-tree.json"));
export const loadSegmentContract = () =>
  readJson<{ thresholds: Record<string, number>; derivation: string[] }>(
    path.join(phase4Dir(), "segment-contract.json")
  );
export const loadSurveySummary = () =>
  readJson<Record<string, unknown>>(path.join(surveyDir(), "survey-summary.json"));
export const loadNomination = () =>
  readJson<Record<string, unknown>>(path.join(phase2Dir(), "nomination.json"));

/** Q1–Q10 research questions with the quotes that answered them (5a). */
export async function loadResearchQuestions() {
  const themes = (await loadThemes()) ?? [];
  const byQuestion = new Map<number, DiscoveryTheme[]>();
  for (const theme of themes) {
    for (const id of theme.researchQuestionIds ?? []) {
      byQuestion.set(id, [...(byQuestion.get(id) ?? []), theme]);
    }
  }

  return [...byQuestion.entries()]
    .sort(([a], [b]) => a - b)
    .map(([id, linked]) => ({
      questionId: id,
      themeIds: linked.map((theme) => theme.id),
      quotes: linked
        .flatMap((theme) => theme.quotes ?? [])
        .filter((quote) => !quote.reviewId.startsWith("fix-") && quote.source !== "fixture")
        .slice(0, 3)
    }));
}
