import { describe, expect, it } from "vitest";
import { evaluateDecisionTree } from "../src/decision-tree.js";
import { buildProblemDefinition } from "../src/problem.js";
import { renderProblemSnippet } from "../src/report.js";
import { computeSignals } from "../src/signals.js";
import { NOMINATION, PRICE_BOUND, RANKING, REALISTIC, inputsFor, summaryFor } from "./fixtures.js";

function lockFor(responses: typeof REALISTIC) {
  const inputs = inputsFor(responses);
  const signals = computeSignals(responses, summaryFor(responses), RANKING);
  const tree = evaluateDecisionTree(signals, NOMINATION);
  return { signals, tree, problem: buildProblemDefinition(inputs, signals, tree) };
}

const { problem, signals } = lockFor(REALISTIC);

describe("six required fields", () => {
  const keys = [
    "targetSegment",
    "productOutcome",
    "rootCause",
    "workarounds",
    "userValue",
    "businessValue"
  ] as const;

  it("fills all six with evidence attached", () => {
    for (const key of keys) {
      const field = problem.fields[key];
      expect(field.statement.length).toBeGreaterThan(40);
      expect(field.evidence.length).toBeGreaterThan(0);
      expect(field.statement).not.toMatch(/\bTBD\b/);
    }
    expect(problem.exitCriteria.sixFieldsFilled).toBe(true);
  });

  it("interpolates counts rather than hard-coding them", () => {
    expect(problem.fields.rootCause.evidence.map((e) => e.detail).join(" ")).toContain("r01, r03, r05, r07");
    expect(problem.fields.targetSegment.statement).toContain("2.89");
  });

  it("carries the in-segment shortfall as a caveat on the segment field", () => {
    expect(problem.fields.targetSegment.caveats.join(" ")).toMatch(/target of 5/);
  });

  it("records the price challenge inside the root cause rather than hiding it", () => {
    expect(problem.fields.rootCause.caveats.join(" ")).toMatch(/never held constant/);
    expect(problem.fields.rootCause.caveats.join(" ")).toMatch(/in-segment respondents chose a discount/);
  });
});

describe("evolution chain", () => {
  it("has no TBD left and ends on an MVP direction", () => {
    expect(problem.evolutionChain.complete).toBe(true);
    expect(problem.evolutionChain.steps).toHaveLength(6);
    expect(problem.evolutionChain.steps.at(-1)?.stage).toBe("MVP direction");
    expect(problem.evolutionChain.steps.at(-1)?.value).toMatch(/Value confidence/);
  });

  it("quotes the discovery corpus size from the pipeline stats", () => {
    const themes = problem.evolutionChain.steps.find((step) => step.stage.startsWith("Themes"));
    expect(themes?.via).toContain("895 raw");
  });
});

describe("quote integrity", () => {
  it("refuses to present fixtures as participant research", () => {
    expect(problem.quotes.participantVerbatimAvailable).toBe(false);
    expect(problem.quotes.reason).toMatch(/no free-text field/);
  });

  it("keeps only live review ids as quotable evidence", () => {
    expect(problem.quotes.liveQuotes.map((q) => q.reviewId)).toEqual([
      "playstore-83ec5f7a",
      "appstore-gb-2-13508351477"
    ]);
    expect(problem.quotes.illustrativeCount).toBe(2);
  });
});

describe("exit criteria and readiness", () => {
  it("passes the Part 4 gate on the delivered data", () => {
    expect(problem.exitCriteria.met).toBe(true);
    expect(problem.exitCriteria.unmet).toEqual([]);
    expect(problem.readyForPhase5).toBe(true);
  });

  it("still refuses Phase 5 when the tree stops", () => {
    const bound = lockFor(PRICE_BOUND);
    expect(bound.tree.outcome).toBe("stop");
    expect(bound.problem.readyForPhase5).toBe(false);
    expect(bound.problem.caveats.join(" ")).toMatch(/documented dead end/);
  });

  it("lists falsification tests for every load-bearing claim", () => {
    expect(problem.falsification.length).toBeGreaterThanOrEqual(5);
    expect(problem.falsification[0]?.falsifiedBy).toMatch(/price explicitly frozen|frozen/);
  });
});

describe("snippet", () => {
  it("renders a paste-ready table marked as generated", () => {
    const snippet = renderProblemSnippet(problem, signals);
    expect(snippet).toMatch(/Generated by phase-4/);
    expect(snippet).toMatch(/\| \*\*Root cause\*\* \|/);
    expect(snippet).toMatch(/Outcome: proceed-rescoped/);
  });
});
