// Generated by phase-4. Contract only — Phase 5a implements this against real user data.
export function matchesStalledShortlister(user: User): boolean {
  if (user.optedOut) return false;

  const recent = user.wishlistItems.filter((i) => i.addedWithinDays(30));
  if (recent.length < 2) return false;

  const purchased = recent.filter((i) => i.purchasedWithinDays(30));
  if (purchased.length > 1) return false;

  const byCategory = groupByCategory(recent);
  return Object.values(byCategory).some((count) => count >= 2);
}
